sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy(effects.confetti, 100)
    info.changeScoreBy(1)
    music.pewPew.play()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.confetti, 100)
    music.baDing.play()
    info.changeLifeBy(-1)
})
let bee: Sprite = null
let clover: Sprite = null
scene.setBackgroundImage(assets.image`background`)
let Raphinha = sprites.create(assets.image`hero`, SpriteKind.Player)
controller.moveSprite(Raphinha)
Raphinha.setStayInScreen(true)
game.onUpdateInterval(2000, function () {
    clover = sprites.createProjectileFromSide(img`
        ....................
        ....................
        ......55555555......
        ....555555555555....
        ...55555555555555...
        .5555555555555555...
        .5555555555555555...
        ..55555555e5555555..
        ....eff5eeee555555..
        ....feeefffe55ee55..
        ....efeeefeee5ee55..
        ....eeeeeeeeeeee5...
        ....eeeeeeeeeeee5...
        ....eeeee11eeee.....
        ....ee1111eeee......
        .....ee11eeee.......
        .....eeeeeee........
        ......eeee..........
        ....................
        ....................
        `, randint(-50, 50), randint(-50, 50))
    bee = sprites.createProjectileFromSide(img`
        ....................
        ....................
        ......fffffffff.....
        .....fffffffffff....
        .....fffffffffff....
        .....feeeeeeeeff....
        .....eeeeeeeeefe....
        .....efffefffeee....
        .....eefeeefeeee....
        .....eeeeeeeeeee....
        .....eeeeeeeeeef....
        .....eeefffeeeef....
        ......efeeefeeef....
        ......eeefeeee......
        .......eeffee.......
        ........ffff........
        ....................
        ....................
        ....................
        ....................
        `, randint(-50, 50), randint(-50, 50))
    bee.setKind(SpriteKind.Enemy)
})
